### ISSUE TITLE
diary.js fails with latest traceur (0.4.1)

### ISSUE THREAD

**Issue by lgersman** [angular/diary.js#10]
when doing something legal like this 

```
Diary.reporter(
    new ConsoleReporter({ console : myconsole })
);
```

diary.js will fail since traceur's Object.assign() polyfill signature has changed. 

change line 31 in src/diary.js from 

```
config = [defaults, config].reduce(Object.assign);
```

to 

```
config = Object.assign( defaults, config);
```

and its fixed.

As far as i've looked into, there is also no testcase for this scenario in diary.js ... thats probably the reason why this issue was not detected before.

**Comment by xmlking** [comment]
+1
without this fix, I am getting this error:

```
TypeError: source must be an object
    at http://localhost:3000/bower_components/es6-shim/es6-shim.js:817:21
    at Object.reduce (native)
    at defineProperties.assign (http://localhost:3000/bower_components/es6-shim/es6-shim.js:815:41)
    at Array.reduce (native)
    at Function.reporter (http://localhost:3000/scripts/diary/diary.js:34:35)
    at http://localhost:3000/scripts/index.js:58:11
    at Object.invoke (http://localhost:3000/bower_components/angular/angular.js:4000:17)
    at http://localhost:3000/bower_components/angular/angular.js:3914:37
    at Array.forEach (native)
    at forEach (http://localhost:3000/bower_components/angular/angular.js:323:11)
```
